//! Vector index materialized view using HNSW (Hierarchical Navigable Small World) graphs.
//!
//! Provides approximate nearest-neighbor search over user-supplied embeddings.
//! Embeddings are NOT generated by ctxd — the caller provides pre-computed
//! embedding vectors, and this view indexes and queries them.
//!
//! # Limitations (v0.1)
//!
//! - **In-memory only**: The HNSW index is not persisted to SQLite. It must be
//!   rebuilt from the event log on restart.
//! - **Rebuild on insert**: `instant-distance` builds an immutable index, so each
//!   insert rebuilds the entire graph. This is acceptable for small-to-medium
//!   workloads in v0.1. A future version may use an incremental index.

use instant_distance::{Builder, HnswMap, Search};
use std::collections::HashMap;

/// Errors from vector view operations.
#[derive(Debug, thiserror::Error)]
pub enum VectorError {
    /// Embedding dimension does not match the view's configured dimensions.
    #[error("dimension mismatch: expected {expected}, got {got}")]
    DimensionMismatch {
        /// Expected dimensionality.
        expected: usize,
        /// Actual dimensionality provided.
        got: usize,
    },
}

/// A point in the embedding space, wrapping a `Vec<f32>`.
#[derive(Clone, Debug)]
struct EmbeddingPoint(Vec<f32>);

impl instant_distance::Point for EmbeddingPoint {
    fn distance(&self, other: &Self) -> f32 {
        // Euclidean distance (L2)
        debug_assert_eq!(self.0.len(), other.0.len());
        self.0
            .iter()
            .zip(other.0.iter())
            .map(|(a, b)| (a - b).powi(2))
            .sum::<f32>()
            .sqrt()
    }
}

/// In-memory HNSW vector index for nearest-neighbor search over event embeddings.
///
/// Stores embeddings alongside event IDs and supports k-nearest-neighbor queries.
/// The index is rebuilt from scratch on each insert (v0.1 limitation).
pub struct VectorView {
    /// Expected dimensionality for all vectors.
    dimensions: usize,
    /// Ordered list of event IDs corresponding to points in the index.
    event_ids: Vec<String>,
    /// The raw embeddings, kept for index rebuilding.
    embeddings: Vec<Vec<f32>>,
    /// Fast lookup from event_id to its index in the vectors.
    id_to_index: HashMap<String, usize>,
    /// The HNSW index. `None` when empty; rebuilt on each insert.
    index: Option<HnswMap<EmbeddingPoint, usize>>,
}

impl VectorView {
    /// Create an empty vector view for embeddings of the given dimensionality.
    pub fn new(dimensions: usize) -> Self {
        Self {
            dimensions,
            event_ids: Vec::new(),
            embeddings: Vec::new(),
            id_to_index: HashMap::new(),
            index: None,
        }
    }

    /// Add a vector embedding associated with an event ID.
    ///
    /// Returns an error if `embedding.len() != self.dimensions`.
    pub fn insert(&mut self, event_id: &str, embedding: Vec<f32>) -> Result<(), VectorError> {
        if embedding.len() != self.dimensions {
            return Err(VectorError::DimensionMismatch {
                expected: self.dimensions,
                got: embedding.len(),
            });
        }

        // If this event_id already exists, update in place.
        if let Some(&idx) = self.id_to_index.get(event_id) {
            self.embeddings[idx] = embedding;
        } else {
            let idx = self.event_ids.len();
            self.event_ids.push(event_id.to_string());
            self.embeddings.push(embedding);
            self.id_to_index.insert(event_id.to_string(), idx);
        }

        self.rebuild_index();
        Ok(())
    }

    /// Search for the `k` nearest neighbors to the given query vector.
    ///
    /// Returns a list of `(event_id, distance)` pairs sorted by ascending distance.
    /// Returns an error if `query.len() != self.dimensions`.
    pub fn search(&self, query: &[f32], k: usize) -> Result<Vec<(String, f32)>, VectorError> {
        if query.len() != self.dimensions {
            return Err(VectorError::DimensionMismatch {
                expected: self.dimensions,
                got: query.len(),
            });
        }

        let index = match &self.index {
            Some(idx) => idx,
            None => return Ok(Vec::new()),
        };

        let query_point = EmbeddingPoint(query.to_vec());
        let mut search = Search::default();
        let results = index.search(&query_point, &mut search);

        Ok(results
            .take(k)
            .map(|item| {
                let point_idx = *item.value;
                let event_id = self.event_ids[point_idx].clone();
                (event_id, item.distance)
            })
            .collect())
    }

    /// Returns the number of vectors in the index.
    pub fn len(&self) -> usize {
        self.event_ids.len()
    }

    /// Returns true if the index is empty.
    pub fn is_empty(&self) -> bool {
        self.event_ids.is_empty()
    }

    /// Rebuild the HNSW index from scratch.
    fn rebuild_index(&mut self) {
        if self.embeddings.is_empty() {
            self.index = None;
            return;
        }

        let points: Vec<EmbeddingPoint> = self
            .embeddings
            .iter()
            .map(|e| EmbeddingPoint(e.clone()))
            .collect();
        let values: Vec<usize> = (0..points.len()).collect();

        let hnsw = Builder::default().build(points, values);
        self.index = Some(hnsw);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn insert_and_len() {
        let mut view = VectorView::new(3);
        assert_eq!(view.len(), 0);
        assert!(view.is_empty());

        view.insert("event-1", vec![1.0, 0.0, 0.0]).unwrap();
        assert_eq!(view.len(), 1);
        assert!(!view.is_empty());
    }

    #[test]
    fn insert_wrong_dimensions() {
        let mut view = VectorView::new(3);
        let err = view.insert("event-1", vec![1.0, 0.0]).unwrap_err();
        assert!(err.to_string().contains("dimension mismatch"));
    }

    #[test]
    fn search_empty_returns_empty() {
        let view = VectorView::new(3);
        let results = view.search(&[1.0, 0.0, 0.0], 5).unwrap();
        assert!(results.is_empty());
    }

    #[test]
    fn search_nearest_neighbors() {
        let mut view = VectorView::new(4);

        // Insert 10 vectors with known positions.
        // Vectors are spread along the first axis.
        for i in 0..10 {
            let embedding = vec![i as f32, 0.0, 0.0, 0.0];
            view.insert(&format!("event-{i}"), embedding).unwrap();
        }
        assert_eq!(view.len(), 10);

        // Query near event-3 (position [3, 0, 0, 0]).
        let query = vec![3.1, 0.0, 0.0, 0.0];
        let results = view.search(&query, 3).unwrap();

        assert_eq!(results.len(), 3);

        // Results should be sorted by ascending distance.
        for window in results.windows(2) {
            assert!(
                window[0].1 <= window[1].1,
                "results not sorted by distance: {} > {}",
                window[0].1,
                window[1].1
            );
        }

        // The nearest neighbor should be event-3.
        assert_eq!(results[0].0, "event-3");
    }

    #[test]
    fn update_existing_event() {
        let mut view = VectorView::new(2);
        view.insert("event-1", vec![1.0, 0.0]).unwrap();
        view.insert("event-1", vec![0.0, 1.0]).unwrap(); // update
        assert_eq!(view.len(), 1); // still one entry

        let results = view.search(&[0.0, 1.0], 1).unwrap();
        assert_eq!(results[0].0, "event-1");
        assert!(results[0].1 < 0.01); // should be very close
    }

    #[test]
    fn search_returns_correct_distances() {
        let mut view = VectorView::new(2);
        view.insert("origin", vec![0.0, 0.0]).unwrap();
        view.insert("one-one", vec![1.0, 1.0]).unwrap();
        view.insert("three-four", vec![3.0, 4.0]).unwrap();

        let results = view.search(&[0.0, 0.0], 3).unwrap();
        assert_eq!(results.len(), 3);

        // Distance from origin to (0,0) should be 0
        assert!((results[0].1 - 0.0).abs() < 1e-6);
        // Distance from origin to (1,1) should be sqrt(2) ~ 1.414
        assert!((results[1].1 - std::f32::consts::SQRT_2).abs() < 0.01);
        // Distance from origin to (3,4) should be 5.0
        assert!((results[2].1 - 5.0).abs() < 0.01);
    }
}
